### PR TITLE
some small fixes

### PR DESCRIPTION
**Pull request by dumboluzz**
- destroying a user now also destroys his alpacas and bookings
- add some top margin to the homepage alpacas to make it more interesting
- in the booking card display the owner name if i am the renter

### CODE REVIEW

**Review by sophiecs333 — APPROVED** [review]
Topitop!

**Review by finnstue — COMMENTED** [review]
nice!

**Review by finnstue — COMMENTED** [review]
good

**Review by finnstue — COMMENTED** [review]
nice

**Pull request merged**
